//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int TravelId { get; set; }
        public string Name { get; set; }
        public int DirectionId { get; set; }
        public int CarId { get; set; }
        public System.DateTime TravelDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Direction Direction { get; set; }
    }
}
